### ISSUE TITLE
Detect deprecated repositories

### ISSUE THREAD

**Issue by Greg-Wilburn** [gabrielcsapo/github-metrics#20]
# Issue
Some repositories shown by this tool are deprecated as indicated in README.md

# Proposal
For repos that wish to support this module, add a `deprecated` tag to the repo as a flag that the code in the module has been deprecated.

# Why?
Do we really need to get metrics on deprecated repos? Probably not. If it is deprecated, work should not be performed any longer.

> But I really want to!

Maybe add a configuration option to enable/disable checks for deprecation.

**Comment by gabrielcsapo** [comment]
You rock @snowinferno! I love this idea, going to implement it and maybe fallback to checking the readme for a deprecated notice
